CREATE TABLE users (
    uid VARCHAR(50) PRIMARY KEY,
    no_user VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100),
    birth_date DATE,
    birth_date_time BIGINT,
    age INT,
    premium BOOLEAN DEFAULT false,
    banned BOOLEAN DEFAULT false,
    afk BOOLEAN DEFAULT false,
    afk_reason TEXT DEFAULT NULL,
    afk_time BIGINT DEFAULT 0,
    autolevelup BOOLEAN DEFAULT true,
    coin INT DEFAULT 0,
    `user_limit` INT DEFAULT 0,
    level INT DEFAULT 1,
    xp INT DEFAULT 0,
    wingame INT DEFAULT 0,
    last_claim_daily BIGINT DEFAULT 0,
    last_claim_weekly BIGINT DEFAULT 0,
    last_claim_monthly BIGINT DEFAULT 0,
    last_claim_yearly BIGINT DEFAULT 0,
    last_claim_limit BIGINT DEFAULT 0,
    registered BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 